### ISSUE TITLE
No module named 'yt_dlp'

### ISSUE THREAD

**Issue by Catley94** [jpetzke/AutoGPT-YouTube#11]
Hey - Tried to download a YouTube video by passing in the URL of the video, however as soon as it touches the script to potentially start looking at downloading, it errors out with the below:

`Welcome to Auto-GPT!  run with '--help' for more information.
Create an AI-Assistant:  input '--manual' to enter manual mode.
  Asking user via keyboard...
I want Auto-GPT to: Please download this YouTube video: https://www.youtube.com/watch?v=3reqAtnFpEs
VDLGPT  has been created with the following details:
Name:  VDLGPT
Role:  an autonomous agent that specializes in video downloading tasks, capable of efficiently and effectively downloading videos from various platforms.
Goals: 
-  Download the YouTube video provided by the user in the highest available quality.
-  Ensure that the downloaded video is free from any errors or corruptions.
-  Provide the user with a notification once the download is complete.
-  Store the downloaded video in a designated folder for easy access by the user.
-  Maintain the privacy and security of the user's information and downloaded content.
Using memory of type:  LocalCache
Using Browser:  chrome
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/sam/autogpt/Auto-GPT-0.3.0/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/autogpt/Auto-GPT-0.3.0/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/home/sam/autogpt/Auto-GPT-0.3.0/autogpt/main.py", line 156, in run_auto_gpt
    system_prompt = ai_config.construct_full_prompt()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/autogpt/Auto-GPT-0.3.0/autogpt/config/ai_config.py", line 147, in construct_full_prompt
    prompt_generator = plugin.post_prompt(prompt_generator)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/AutoGPT-YouTube-master.zip/AutoGPT-YouTube-master/src/autogpt_youtube/__init__.py", line 61, in post_prompt
  File "plugins/AutoGPT-YouTube-master.zip/AutoGPT-YouTube-master/src/autogpt_youtube/youtube_download.py", line 1, in <module>
ModuleNotFoundError: No module named 'yt_dlp'
Press any key to continue...
`

I'm not very proficient (yet) in python, but it is a language that I'm currently learning on the side, so happy to help, if I find anything, I'll update this issue here, otherwise, if you know how to fix - please let me know :-)

EDIT: I can see the file "yt_dlp" under venv/bin/ so it's definitely there and also under venv/lib/yt_dlp.

**Comment by Catley94** [comment]
I did, I ran pip install -r requirements.txt 

Is this the correct command?

**Comment by reaganfry** [comment]
I am having the same issue. Installed requirements.txt from the YT plugin folder, but getting same error message as above

**Comment by joshua-philip** [comment]
Make sure your PATH variable is set to your newest version of Python, and there arent multiple. If you have two versions, for example, 3.10 and 3.11, and the requirements were installed in the 3.11 folder, but you're program is using 3.10, it won't work. Double check you only have one version in your environment variables.

**Comment by reaganfry** [comment]
Only have one PATH so I dont think is that. I tried changing the requirements.txt / youtube_download.py from '_' to '-' and it throws a syntax error

**Comment by jpetzke** [comment]
Can you show me the code snippet that is affected and the error message?

**Comment by llfsdog** [comment]
I'm also having the same problem, how can I fix it?
