### ISSUE TITLE
WARNING  Cannot add command

### ISSUE THREAD

**Issue by rsindall** [jpetzke/AutoGPT-YouTube#24]
I am running AutoGPT 0.5.0 in Docker

I've added the YT plugin, and added an API key, but when AutoGPT tries to use the plugin, I get this error:

2024-02-02 23:08:53,939 WARNING  Cannot add command 'go_to_website': parameter 'url' has invalid type '<url>'. Valid types are: dict_keys(['string', 'array', 'object', 'number', 'integer', 'boolean'])
2024-02-02 23:08:53,940 WARNING  Cannot add command 'click_element_by_id': parameter 'id' has invalid type '<id>'. Valid types are: dict_keys(['string', 'array', 'object', 'number', 'integer', 'boolean'])
2024-02-02 23:08:53,940 WARNING  Cannot add command 'input_text_by_id': parameter 'id' has invalid type '<id>'. Valid types are: dict_keys(['string', 'array', 'object', 'number', 'integer', 'boolean'])
2024-02-02 23:08:53,942 WARNING  Cannot add command 'input_text_by_id_and_press_enter': parameter 'id' has invalid type '<id>'. Valid types are: dict_keys(['string', 'array', 'object', 'number', 'integer', 'boolean'])
2024-02-02 23:08:53,943 WARNING  Cannot add command 'scroll': parameter 'direction' has invalid type '<directionToScroll>'. Valid types are: dict_keys(['string', 'array', 'object', 'number', 'integer', 'boolean'])
2024-02-02 23:08:54,392 WARNING  Cannot add command 'download_youtube_video': parameter 'url' has invalid type '<video url>'. Valid types are: dict_keys(['string', 'array', 'object', 'number', 'integer', 'boolean'])
2024-02-02 23:08:54,392 WARNING  Cannot add command 'download_youtube_audio': parameter 'url' has invalid type '<video url>'. Valid types are: dict_keys(['string', 'array', 'object', 'number', 'integer', 'boolean'])
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/agpt-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/venv/agpt-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/venv/agpt-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/venv/agpt-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/venv/agpt-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/app/autogpt/app/cli.py", line 177, in run
    run_auto_gpt(
  File "/app/autogpt/core/runner/client_lib/utils.py", line 60, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/autogpt/app/main.py", line 292, in run_auto_gpt
    await run_interaction_loop(agent)
  File "/app/autogpt/app/main.py", line 489, in run_interaction_loop
    ) = await agent.propose_action()
  File "/app/autogpt/agents/features/watchdog.py", line 36, in propose_action
    command_name, command_args, thoughts = await super(
  File "/app/autogpt/agents/base.py", line 246, in propose_action
    prompt: ChatPrompt = self.build_prompt(scratchpad=self._prompt_scratchpad)
  File "/app/autogpt/agents/agent.py", line 146, in build_prompt
    return super().build_prompt(
  File "/app/autogpt/agents/features/context.py", line 71, in build_prompt
    return super(ContextMixin, self).build_prompt(
  File "/app/autogpt/agents/base.py", line 311, in build_prompt
    plugin.post_prompt(scratchpad)
  File "plugins/AutoGPT-YouTube-master.zip/AutoGPT-YouTube-master/src/autogpt_youtube/__init__.py", line 76, in post_prompt
    from .youtube_functions import get_youtube_transcript
  File "plugins/AutoGPT-YouTube-master.zip/AutoGPT-YouTube-master/src/autogpt_youtube/youtube_functions.py", line 2, in <module>
    import nltk
ModuleNotFoundError: No module named 'nltk'

**Comment by rsindall** [comment]
Full Error

```
2024-02-02 23:08:53,939 WARNING  Cannot add command 'go_to_website': parameter 'url' has invalid type '<url>'. Valid types are: dict_keys(['string', 'array', 'object', 'number', 'integer', 'boolean'])
2024-02-02 23:08:53,940 WARNING  Cannot add command 'click_element_by_id': parameter 'id' has invalid type '<id>'. Valid types are: dict_keys(['string', 'array', 'object', 'number', 'integer', 'boolean'])
2024-02-02 23:08:53,940 WARNING  Cannot add command 'input_text_by_id': parameter 'id' has invalid type '<id>'. Valid types are: dict_keys(['string', 'array', 'object', 'number', 'integer', 'boolean'])
2024-02-02 23:08:53,942 WARNING  Cannot add command 'input_text_by_id_and_press_enter': parameter 'id' has invalid type '<id>'. Valid types are: dict_keys(['string', 'array', 'object', 'number', 'integer', 'boolean'])
2024-02-02 23:08:53,943 WARNING  Cannot add command 'scroll': parameter 'direction' has invalid type '<directionToScroll>'. Valid types are: dict_keys(['string', 'array', 'object', 'number', 'integer', 'boolean'])
2024-02-02 23:08:54,392 WARNING  Cannot add command 'download_youtube_video': parameter 'url' has invalid type '<video url>'. Valid types are: dict_keys(['string', 'array', 'object', 'number', 'integer', 'boolean'])
2024-02-02 23:08:54,392 WARNING  Cannot add command 'download_youtube_audio': parameter 'url' has invalid type '<video url>'. Valid types are: dict_keys(['string', 'array', 'object', 'number', 'integer', 'boolean'])
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/agpt-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/venv/agpt-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/venv/agpt-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/venv/agpt-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/venv/agpt-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/app/autogpt/app/cli.py", line 177, in run
    run_auto_gpt(
  File "/app/autogpt/core/runner/client_lib/utils.py", line 60, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/autogpt/app/main.py", line 292, in run_auto_gpt
    await run_interaction_loop(agent)
  File "/app/autogpt/app/main.py", line 489, in run_interaction_loop
    ) = await agent.propose_action()
  File "/app/autogpt/agents/features/watchdog.py", line 36, in propose_action
    command_name, command_args, thoughts = await super(
  File "/app/autogpt/agents/base.py", line 246, in propose_action
    prompt: ChatPrompt = self.build_prompt(scratchpad=self._prompt_scratchpad)
  File "/app/autogpt/agents/agent.py", line 146, in build_prompt
    return super().build_prompt(
  File "/app/autogpt/agents/features/context.py", line 71, in build_prompt
    return super(ContextMixin, self).build_prompt(
  File "/app/autogpt/agents/base.py", line 311, in build_prompt
    plugin.post_prompt(scratchpad)
  File "plugins/AutoGPT-YouTube-master.zip/AutoGPT-YouTube-master/src/autogpt_youtube/__init__.py", line 76, in post_prompt
    from .youtube_functions import get_youtube_transcript
  File "plugins/AutoGPT-YouTube-master.zip/AutoGPT-YouTube-master/src/autogpt_youtube/youtube_functions.py", line 2, in <module>
    import nltk
```
