### ISSUE TITLE
Plugin does not run on MacOS 

### ISSUE THREAD

**Issue by yogisss** [jpetzke/AutoGPT-YouTube#4]
Hi,
on MacOS the launch of AutoGPT fails with the following error on launch when AutoGPT-Youtube is in the plugins folder:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/yogi/Significant-Gravitas/Auto-GPT/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yogi/Significant-Gravitas/Auto-GPT/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/Users/yogi/Significant-Gravitas/Auto-GPT/autogpt/main.py", line 104, in run_auto_gpt
    cfg.set_plugins(scan_plugins(cfg, cfg.debug_mode))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yogi/Significant-Gravitas/Auto-GPT/autogpt/plugins.py", line 218, in scan_plugins
    zipped_module = zipped_package.load_module(str(module.parent))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen zipimport>", line 283, in load_module
  File "<frozen zipimport>", line 778, in _get_module_code
zipimport.ZipImportError: can't find module '__MACOSX/AutoGPT-YouTube-master/src/autogpt_youtube'

**Comment by yogisss** [comment]
Thank you for your reply! I installed everything new with the current master branch of AutoGPT -> seems to work now. Sorry for bothering you!

**Comment by jpetzke** [comment]
No problem, it was probably fixed by some of the updates I've made in the meantime
